### PR TITLE
Last changes!!

### PR DESCRIPTION
**Pull request by elemikelo**
Rename files: 
/index.js --> /server.js,
/routes/index.js --> api.js,
/controllers/index.js --> api.js

Changed:
code error 500 and request format json.

note: included '.DS_Store' in .gitignore.

### CODE REVIEW

**Comment by UlisesGascon** [comment]
Hi @elemikelo! 
All the changes looks great, but... 

```javascript
return res.status(500).json({success: false, message: err.message })
```

It is not a good practise to send to the client the error message, as this information potentially contains critical data. This sensitive information can be used by hackers... in the future. As this information is important, you can show the info in the console.

Please change it... and I will approve the merge.

**Comment by carquet** [comment]
Change it to what? I understand the problem but I don't understand what it should be changed into.

**Comment by carquet** [comment]
What is ds_store?

**Comment by elemikelo** [comment]
Are files that the mac osx operating system creates :)

**Comment by UlisesGascon** [comment]
Movido a #31 por problemas de mergeos

**Pull request closed without merging**
